### ISSUE TITLE
Not watching entry point for hard reset.

### ISSUE THREAD

**Issue by marcoancona** [yan-foto/electron-reload#17]
It seems hard reset is never triggered in my app, cause it creates a watcher that points to `app.getAppPath()`. 
This path is `default-app.asar` inside the electron's node-module folder. This is not my app entrypoint.
This issue might be related to the use of `.getAppPath()`? 
http://stackoverflow.com/questions/40511744/what-is-electrons-app-getapppath-pointing-to

**Comment by yan-foto** [comment]
You should provide more information: is this a packaged app, on which platform are you running this, etc.

**Comment by marcoancona** [comment]
It's not packaged cause I am using electron-reload in development only. I am using browserify to collect all the source code and combine it into a `./dist/main.js` for the main process. 
My package.json looks like:

**Comment by marcoancona** [comment]
As proof of concept I replaced
```js
let appPath = app.getAppPath();
```
with 
```js
let appPath = options.appPath || app.getAppPath();
```
to accept the root path as parameter and I am able to have it work as expected passing `process.cwd()`

**Comment by yan-foto** [comment]
The [documentation](https://github.com/electron/electron/blob/master/docs/api/app.md#appgetapppath) states:

> `app.getAppPath()`
> Returns `String` - The current application directory.

And since this is the first occurrence (to my knowledge) that it returns path to `.asar` package, I need to be able to reproduce the problem before finding a solution for it.

The suggested work around does not address the actual problem it just goes around it!

**Comment by yan-foto** [comment]
For lack of activity and more information, I will close this issue for now.
